const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Flash,
		C3.Behaviors.wackytoasterSavestate,
		C3.Behaviors.Tween,
		C3.Behaviors.Follow,
		C3.Behaviors.solid,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.wrap,
		C3.Behaviors.Persist,
		C3.Plugins.progressbar,
		C3.Behaviors.MoveTo,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.custom,
		C3.Behaviors.jumpthru,
		C3.Plugins.Particles,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.Rotate,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.Function,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Browser,
		C3.Plugins.Camera3D,
		C3.Plugins.gamepad,
		C3.Plugins.LocalStorage,
		C3.Plugins.BinaryData,
		C3.Plugins.FileSystem,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Bluetooth,
		C3.Plugins.DrawingCanvas,
		C3.Behaviors.Turret,
		C3.Plugins.Multiplayer,
		C3.Plugins.video,
		C3.Plugins.GameRecorder,
		C3.Plugins.Date,
		C3.Plugins.sliderbar,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.shadowlight,
		C3.Plugins.Shape3D,
		C3.Plugins.Tilemap,
		C3.Plugins.Timeline,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.solid.Cnds.IsEnabled,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.min,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.originalwindowwidth,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.originalwindowheight,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Audio.Exps.MasterVolume,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.tickcount,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.TiledBg.Exps.UID,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Sprite.Acts.ToggleBoolInstanceVar,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.LOS.Acts.SetRange,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Exps.Volume,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Cnds.CompareY,
		C3.Plugins.TiledBg.Acts.SetMeshPoint,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.Date.Exps.GetHours,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.TiledBg.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.PlatformInfo.Acts.RequestWakeLock,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.AddAnalyserEffect,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Acts.SetSpeed,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Behaviors.Follow.Acts.SetDelay,
		C3.Behaviors.Follow.Acts.SetMaxDelay,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Follow.Acts.StartFollowingCustomProperty,
		C3.Behaviors.Follow.Exps.DelayedCustomPropertyValue,
		C3.Behaviors.Follow.Acts.SetCustomPropertyValue,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Audio.Acts.SetEffectParameter,
		C3.Plugins.FileSystem.Acts.WriteBinaryFile,
		C3.Plugins.BinaryData.Acts.SetInstanceVar,
		C3.Plugins.FileSystem.Acts.WriteTextFile,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Cnds.OnLoadComplete,
		C3.Plugins.Audio.Acts.PlayAtObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Audio.Exps.Duration,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.OnResume,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Behaviors.Physics.Acts.CreateDistanceJoint,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Behaviors.Physics.Cnds.CompareAngularVelocity,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Audio.Acts.SetListenerObject,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.System.Acts.SetLayerTransparent,
		C3.Plugins.System.Acts.SetLayerBackground,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Behaviors.Physics.Acts.ApplyForceToward,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Cnds.IsByWall,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Exps.Speed,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Spritefont2.Acts.SetCharacterSpacing,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.SetLayerEffectEnabled,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Spritefont2.Exps.IID,
		C3.Plugins.Spritefont2.Exps.Count,
		C3.Plugins.Spritefont2.Cnds.CompareX,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.DrawingCanvas.Acts.ClearCanvas,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.DrawingCanvas.Acts.SetPos,
		C3.Plugins.DrawingCanvas.Exps.X,
		C3.Plugins.DrawingCanvas.Exps.Width,
		C3.Plugins.DrawingCanvas.Exps.Y,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.Tween.Exps.Value,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Behaviors.Follow.Acts.SetPaused,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.gamepad.Cnds.OnButtonUp,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.PlatformInfo.Cnds.IsOniOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.PlatformInfo.Cnds.IsOnLinux,
		C3.Plugins.PlatformInfo.Cnds.IsOnMacOS,
		C3.Plugins.PlatformInfo.Cnds.IsOnChromeOS,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.gamepad.Acts.VibrateDualRumble,
		C3.Plugins.gamepad.Cnds.OnGamepadConnected,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.gamepad.Cnds.HasGamepads,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.GameRecorder.Acts.StartRecording2,
		C3.Plugins.GameRecorder.Acts.StopRecording,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.GameRecorder.Exps.RecordingURL,
		C3.Plugins.GameRecorder.Cnds.SupportsRecording,
		C3.Plugins.Browser.Acts.Alert,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.Plugins.Browser.Exps.Platform,
		C3.Plugins.Multiplayer.Cnds.OnSignallingConnected,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLoggedIn,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.TextBox.Acts.SetReadOnly,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.Button.Acts.SetEnabled,
		C3.Plugins.Multiplayer.Cnds.IsHost,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.System.Exps.roundtodp,
		C3.JavaScriptInEvents["Menu&OptionsScreen_Event1"],
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.BinaryData.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLoadFailed,
		C3.Plugins.Date.Exps.ToLocaleTimeString,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Behaviors.Flash.Acts.StopFlashing,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.TiledBg.Exps.Opacity,
		C3.JavaScriptInEvents.LayoutScreen_Event1,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.System.Acts.ScrollY,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.System.Acts.SetLayerEffectParam,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Audio.Exps.PlaybackTime,
		C3.Plugins.Audio.Acts.Seek,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.System.Acts.SetLayoutEffectParam,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Timeline.Acts.StopAllTimelines,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Exps.TotalTime,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Cnds.IsEnabled
	];
};
self.C3_JsPropNameTable = [
	{Collision: 0},
	{Offset: 0},
	{Player_MaskBottom: 0},
	{Player_MaskBottomDetector: 0},
	{XPos: 0},
	{YPos: 0},
	{Height1: 0},
	{Height2: 0},
	{Slopes: 0},
	{CountXPos: 0},
	{Player_MaskEdgeCheck: 0},
	{Player_MaskLeft: 0},
	{Distance: 0},
	{Player_MaskLeftAngle: 0},
	{Player_MaskLeftBig: 0},
	{Offset2: 0},
	{Player_MaskLeftLine: 0},
	{Player_MaskMain: 0},
	{Player_MaskRight: 0},
	{Player_MaskRightAngle: 0},
	{Player_MaskRightBig: 0},
	{Player_MaskRightLine: 0},
	{Player_MaskTop: 0},
	{Player_MaskTopBig: 0},
	{AllowMovement: 0},
	{AllowJump: 0},
	{X_Float: 0},
	{X_Float_Old: 0},
	{X_Speed: 0},
	{X_Speed_Add: 0},
	{X_Speed_Add_Dcc: 0},
	{X_Speed_Add_Air: 0},
	{X_Speed_Max: 0},
	{X_Speed_Top: 0},
	{X_ControlLock: 0},
	{Y_Float: 0},
	{Y_Float_Old: 0},
	{Y_Speed: 0},
	{Y_Speed_Add: 0},
	{Y_Speed_AirDrag: 0},
	{Y_Speed_Max: 0},
	{Y_JumpSpeed: 0},
	{Action: 0},
	{Ground: 0},
	{Current_Angle: 0},
	{Smooth_Angle: 0},
	{Skin_Angle: 0},
	{Character_Direction: 0},
	{Falling_Check_Flag: 0},
	{Landing_Flag: 0},
	{Ceiling_Landing_Flag: 0},
	{Slope: 0},
	{Slope_Dcc_Factor: 0},
	{Slope_Dcc_Roll_Down: 0},
	{Slope_Dcc_Roll_Up: 0},
	{Rolling_Break: 0},
	{Rolling_Dcc: 0},
	{Skidding: 0},
	{Skidding_Effect_Timer: 0},
	{CurrentAnimation: 0},
	{SpeedAnimation: 0},
	{Spindash: 0},
	{HurtTimer: 0},
	{DieTimer: 0},
	{WhatWasX_Speed: 0},
	{WhatWasY_Speed: 0},
	{Quickdash: 0},
	{CombatMode: 0},
	{PunchPower: 0},
	{InWater: 0},
	{InDebugMode: 0},
	{Spin: 0},
	{peerid: 0},
	{HomingAttack: 0},
	{Bound_X: 0},
	{PassThru: 0},
	{Walkpast: 0},
	{FallDamage: 0},
	{Shocked: 0},
	{OnSlope: 0},
	{Player_A_Physics: 0},
	{Victory: 0},
	{WalktoNext: 0},
	{PunchorKick: 0},
	{Frame: 0},
	{Flash: 0},
	{Savestate: 0},
	{Tween: 0},
	{skinToco: 0},
	{Player_Mask_Sensor_Collect: 0},
	{Flipped: 0},
	{Follow: 0},
	{skinVoltFollower: 0},
	{Passhit: 0},
	{Solid: 0},
	{Player_OnEdgeLeft: 0},
	{Moving: 0},
	{Pathfinding: 0},
	{VoltCameo: 0},
	{skinVolt2: 0},
	{Mirrored: 0},
	{id: 0},
	{skinTocoblur: 0},
	{LineOfSight: 0},
	{Angler: 0},
	{White: 0},
	{Player_OnEdgeRight: 0},
	{DebugObjectSpawner: 0},
	{Ring: 0},
	{RingLoss: 0},
	{XFloat: 0},
	{YFloat: 0},
	{RSpeed: 0},
	{RGravity: 0},
	{RTimer: 0},
	{Ring2: 0},
	{RingAmount: 0},
	{RingCount: 0},
	{RingCCount: 0},
	{Ring3: 0},
	{Ball: 0},
	{SpringYellow: 0},
	{SpringRed: 0},
	{SpeedBooster: 0},
	{SpringBlue: 0},
	{Ejecting: 0},
	{Spikes: 0},
	{"1upmonitor": 0},
	{WarningSign: 0},
	{Door1: 0},
	{Health: 0},
	{Anim: 0},
	{Quick: 0},
	{Wait: 0},
	{RollorCombat: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Physics: 0},
	{EnemyandBoss: 0},
	{AirBubbleCreator: 0},
	{BigAirbubble: 0},
	{Shieldmonitor: 0},
	{Shield: 0},
	{Invincable: 0},
	{Invincmonitor: 0},
	{Crusher: 0},
	{Planet1: 0},
	{Planet2: 0},
	{Sine3: 0},
	{Planet3: 0},
	{DoorOpener1: 0},
	{DoorSensor: 0},
	{FlagTrue: 0},
	{LvlTxt1: 0},
	{Spacedown: 0},
	{Spacing: 0},
	{LvlTxt2: 0},
	{Countdown: 0},
	{LvlTxt3: 0},
	{LvlTxt4: 0},
	{LvlTxt5: 0},
	{Yoffset: 0},
	{EjectingSpikes: 0},
	{skinDalx: 0},
	{Door2: 0},
	{Lever1: 0},
	{Light1: 0},
	{Wrap: 0},
	{Light2: 0},
	{Checked: 0},
	{Persist: 0},
	{Checkpoint: 0},
	{XSpeed: 0},
	{YSpeed: 0},
	{ZSpeed: 0},
	{MonitorDebris: 0},
	{Fallcheck: 0},
	{XMesh1: 0},
	{YMesh1: 0},
	{Speed: 0},
	{Mounted: 0},
	{LocoBody1: 0},
	{Wheel1: 0},
	{Wheel2: 0},
	{Wheel3: 0},
	{LocoPlayerCollision: 0},
	{LocoBody2: 0},
	{LocoPlayerCollision2: 0},
	{E3Wheel1: 0},
	{E3Wheel2: 0},
	{E3Wheel3: 0},
	{CargoWheel1: 0},
	{CargoWheel2: 0},
	{CargoBody1: 0},
	{WaterPartical: 0},
	{LevelSelectText: 0},
	{LevelSelectST: 0},
	{HUD_Life: 0},
	{HUD_Rings: 0},
	{HUD_Score: 0},
	{LevelTimer: 0},
	{Rings: 0},
	{HUD_Text: 0},
	{Lives: 0},
	{HUD_TextLife: 0},
	{HUD_Time: 0},
	{HUD_Pause: 0},
	{PauseUIResume: 0},
	{SelectingStr: 0},
	{SelectingNum: 0},
	{PauseUIBG: 0},
	{PauseUIRestart: 0},
	{PauseUIMainMenu: 0},
	{HUD_BOSSHEALTH: 0},
	{PauseUIBorder: 0},
	{PauseUIGrayscaler: 0},
	{TitleCard_Banner: 0},
	{TitleCard_Black: 0},
	{TitleCard_NameStage: 0},
	{TitleCard_Zone: 0},
	{TitleCard_Zone2Act: 0},
	{ProgressBar: 0},
	{Jog: 0},
	{TocoJoging: 0},
	{VoltJoging: 0},
	{Sprite17: 0},
	{A: 0},
	{B: 0},
	{TitleLogo: 0},
	{Sprite20: 0},
	{MoveTo: 0},
	{SpriteFont: 0},
	{SpriteFont2: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{SpriteFont3: 0},
	{LayoutsComplete: 0},
	{Options: 0},
	{Start: 0},
	{MusicPlaying: 0},
	{TTHTitleLay: 0},
	{TTHTitleLay2Bmp: 0},
	{costume: 0},
	{Continue: 0},
	{OptionsMusicDisplay: 0},
	{MusicType: 0},
	{OptionsMusicType: 0},
	{CreditsText: 0},
	{OptionsFullscreenText: 0},
	{OptionsFullscreenType: 0},
	{OptionsSoundTestText: 0},
	{TestSound: 0},
	{z: 0},
	{OptionsSoundTestDisplay: 0},
	{OptionsControlTypeText: 0},
	{OptionsControlTypeInput: 0},
	{VersionTxt1: 0},
	{Layout1Text: 0},
	{Layout1Text2: 0},
	{Layout1Text3: 0},
	{Layout1Text4: 0},
	{Layout1Text5: 0},
	{OptionsBGMVolumeText: 0},
	{OptionsBGMVolumeDisplay: 0},
	{LoadingTxt: 0},
	{OptionsONLMULT: 0},
	{TitleLogo2: 0},
	{TheTime: 0},
	{OptionsMainMenuMusictype: 0},
	{pX: 0},
	{pY: 0},
	{targetX: 0},
	{targetY: 0},
	{mode: 0},
	{groundOffset: 0},
	{PreviousGroundState: 0},
	{ScrollOffset: 0},
	{TimeuntilOffset: 0},
	{Flip: 0},
	{SystemCamera: 0},
	{ColorRed: 0},
	{ColorGreen: 0},
	{ColorBlue: 0},
	{Fade: 0},
	{FadeSpeed: 0},
	{FadeStyle: 0},
	{SystemFade: 0},
	{SystemFade2: 0},
	{WrapperBottom: 0},
	{WrapperTop: 0},
	{Ramp3: 0},
	{QuarterCircle1: 0},
	{QuarterCircle2: 0},
	{QuarterCircle3: 0},
	{Sprite15: 0},
	{Slope1: 0},
	{"2x2Block": 0},
	{Block: 0},
	{Block2: 0},
	{Slope3: 0},
	{QuarterCircle4: 0},
	{TiledBackground: 0},
	{Ramp1: 0},
	{ScrollTo: 0},
	{Custom: 0},
	{Sprite11: 0},
	{RollerBlock: 0},
	{halfblock: 0},
	{Jumpthru: 0},
	{PassthuBlock: 0},
	{Wedge: 0},
	{Wedge2: 0},
	{Wedge3: 0},
	{Ramp2: 0},
	{"3quarterBlock": 0},
	{Blockx2: 0},
	{Blockx4: 0},
	{LeftLoopdetecter: 0},
	{RightLoopdeloopbottom: 0},
	{RightLoopdetecter: 0},
	{LeftLoopdeloopbottom: 0},
	{RightMiddle: 0},
	{LeftMiddle: 0},
	{"2x2Blocknocollision": 0},
	{PassthuBlock2: 0},
	{TiledBackground5: 0},
	{Sprite2: 0},
	{add: 0},
	{Sine: 0},
	{Sine2: 0},
	{Sprite4: 0},
	{Rod: 0},
	{Rod2: 0},
	{RodCollision: 0},
	{Slope2: 0},
	{XOffset: 0},
	{FloatingBlockx4: 0},
	{Player_X_Offset: 0},
	{FloatingBlockX: 0},
	{"4x4Block": 0},
	{Glider: 0},
	{"4x2Block": 0},
	{PassableRamp: 0},
	{BGLayer1: 0},
	{BGLayer2: 0},
	{BGLayer3: 0},
	{BGLayer4: 0},
	{BGLayer0: 0},
	{TiledBackground8: 0},
	{RollerBlockStart: 0},
	{RollerBlockEnd: 0},
	{DrowningCountdown: 0},
	{Water: 0},
	{TiledBackground10: 0},
	{MML1BG: 0},
	{MML1BG2: 0},
	{"2x2Blocknocollision2": 0},
	{TiledBackground13: 0},
	{Ramp4: 0},
	{Gliderwithcollision1: 0},
	{Glider2: 0},
	{Gliders: 0},
	{TiledBackground11: 0},
	{Blockdetecter1: 0},
	{Blockdetecter2: 0},
	{PassthruOff: 0},
	{PassthruOn: 0},
	{TiledBackground14: 0},
	{Shocker: 0},
	{TileBlock: 0},
	{"2x2Block2": 0},
	{Water2: 0},
	{Effect_SkiddingDust: 0},
	{Effect_Spindash: 0},
	{Boom: 0},
	{Effect_Explosion: 0},
	{Splash: 0},
	{Effects_Sparkle: 0},
	{Effects_Sparkle2: 0},
	{Effect_Burst: 0},
	{Effects_Sparkle3: 0},
	{Effects_Sparkle4: 0},
	{Effect_Electricity: 0},
	{Loco_Exaust: 0},
	{Loco_Exaust2: 0},
	{Loco_Exaust3: 0},
	{Loco_Exaust4: 0},
	{E3Loco_Exaust: 0},
	{WaterWaves: 0},
	{TPad_Action: 0},
	{Touch_Down: 0},
	{Touch_Left: 0},
	{Touch_Right: 0},
	{Touch_Up: 0},
	{TPad_Control: 0},
	{Ignore: 0},
	{InputUp: 0},
	{InputUpPressed: 0},
	{InputDown: 0},
	{InputDownPressed: 0},
	{InputLeft: 0},
	{InputLeftPressed: 0},
	{InputRight: 0},
	{InputRightPressed: 0},
	{InputAction: 0},
	{InputActionPressed: 0},
	{InputAny: 0},
	{Player_Input: 0},
	{TPad_Quickdash: 0},
	{TPad_Speedometer: 0},
	{TPad_Speedometer2: 0},
	{TPad_Combat: 0},
	{MenuLeftInput: 0},
	{MenuRightInput: 0},
	{MenuSelectInput: 0},
	{Cursor: 0},
	{Player_Input2: 0},
	{TPad_Speedometer3: 0},
	{Player_MaskBottom2: 0},
	{Player_MaskBottomDetector2: 0},
	{Player_MaskEdgeCheck2: 0},
	{Player_MaskLeft2: 0},
	{Player_MaskLeftAngle2: 0},
	{Player_MaskLeftBig2: 0},
	{Player_MaskLeftLine2: 0},
	{Player_MaskMain2: 0},
	{Player_MaskRight2: 0},
	{Player_MaskRightAngle2: 0},
	{Player_MaskRightBig2: 0},
	{Player_MaskRightLine2: 0},
	{Player_MaskTop2: 0},
	{Player_MaskTopBig2: 0},
	{AItimer: 0},
	{StuckTimer: 0},
	{Player_B_Physics: 0},
	{skinVolt: 0},
	{Player_Mask_Sensor_Collect2: 0},
	{skinVoltFollower2: 0},
	{Passhit2: 0},
	{Player_OnEdgeLeft2: 0},
	{VoltCameo2: 0},
	{skinVolt3: 0},
	{Angler2: 0},
	{White2: 0},
	{Bullet: 0},
	{EyeFire: 0},
	{Timer: 0},
	{EnergyBeam: 0},
	{IDName: 0},
	{BossHips: 0},
	{Blink: 0},
	{ShootFireBall: 0},
	{BossHead: 0},
	{Detonate: 0},
	{Trail: 0},
	{BossFrontArm: 0},
	{BossChest: 0},
	{BossBackArm: 0},
	{Explosion: 0},
	{EyeFlash: 0},
	{FireBall: 0},
	{FireBallTrail: 0},
	{FrontArmTrail: 0},
	{Rotate: 0},
	{DestroyOutsideLayout: 0},
	{GroundDebri: 0},
	{BigExplosion: 0},
	{Audio: 0},
	{Function: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Sprite3: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Goal: 0},
	{Mouse: 0},
	{Touch: 0},
	{Back: 0},
	{SondrixLogo: 0},
	{Text: 0},
	{Sondrix: 0},
	{Browser: 0},
	{Untitled11_: 0},
	{dczd4eg83f90a47ff0c432e9c56b64ccd85d16c: 0},
	{logo: 0},
	{Sprite5: 0},
	{"3DCamera": 0},
	{Sprite10: 0},
	{Sprite16: 0},
	{Sprite18: 0},
	{Sprite21: 0},
	{Sprite23: 0},
	{TiledBackground6: 0},
	{TiledBackground7: 0},
	{GameOverText: 0},
	{Sprite24: 0},
	{Sprite25: 0},
	{GoalWall: 0},
	{GoalCover: 0},
	{Sprite22: 0},
	{ResultsUITotalScoreText: 0},
	{ResultsUIMadeitText: 0},
	{ResultsUIRingsText: 0},
	{ResultsUITimeText: 0},
	{ResultsUITime: 0},
	{ResultsUIRing: 0},
	{TimeScore: 0},
	{RingScore: 0},
	{TotalScore: 0},
	{ResultsUITotalScore: 0},
	{Gamepad: 0},
	{Sprite26: 0},
	{Dont: 0},
	{Sprite27: 0},
	{LocalStorage: 0},
	{ContinueTo: 0},
	{BGMwas: 0},
	{RecentBGM: 0},
	{BinaryData: 0},
	{Muted: 0},
	{Mute: 0},
	{Killer: 0},
	{FileSystem: 0},
	{SpriteFont4: 0},
	{TiledBackground9: 0},
	{VoltIcon: 0},
	{Arrow: 0},
	{PlatformInfo: 0},
	{Bluetooth: 0},
	{DrawingCanvas: 0},
	{Emblem: 0},
	{Turret: 0},
	{Sprite6: 0},
	{Multiplayer: 0},
	{Sprite28: 0},
	{Video: 0},
	{GoalCover2: 0},
	{SEGA: 0},
	{ConstructLogo: 0},
	{ConstuctText: 0},
	{Sprite29: 0},
	{VideoRecorder: 0},
	{Sprite30: 0},
	{ContinueIcon: 0},
	{Template1: 0},
	{Sprite19: 0},
	{TiledBackground12: 0},
	{Sprite31: 0},
	{Date: 0},
	{SliderBar: 0},
	{Buildings: 0},
	{Sprite7: 0},
	{TextInput: 0},
	{Button: 0},
	{TextInput2: 0},
	{Sprite12: 0},
	{TiledBackground15: 0},
	{Text2: 0},
	{SliderBar2: 0},
	{Zoom: 0},
	{InitialX: 0},
	{InitialY: 0},
	{Slide: 0},
	{Rotation: 0},
	{SondrixLetter: 0},
	{Sprite13: 0},
	{Static: 0},
	{SondrixLoadingthing: 0},
	{Sprite14: 0},
	{ShadowLight: 0},
	{Sprite32: 0},
	{Banner: 0},
	{Sprite33: 0},
	{"3DShape": 0},
	{Sprite34: 0},
	{Glass: 0},
	{SonicCameo: 0},
	{Text3: 0},
	{NiseEU: 0},
	{SonicFollower: 0},
	{TitlecardLetters: 0},
	{Particles: 0},
	{Sprite35: 0},
	{IIL1BG1: 0},
	{IIL1Clouds: 0},
	{IIL1BG2: 0},
	{SCL2BG1: 0},
	{Cloud1: 0},
	{Cloud2: 0},
	{Cloud3: 0},
	{Cloud4: 0},
	{Cloud5: 0},
	{Cloud6: 0},
	{Cloud7: 0},
	{TiledBackground23: 0},
	{TiledBackground24: 0},
	{LocoRod: 0},
	{PPL1BG1: 0},
	{PPL1BG2: 0},
	{PPL1BG3: 0},
	{PPL1BG4: 0},
	{PPL1BG5: 0},
	{Particles2: 0},
	{E3LocoRod1: 0},
	{IIL1Foreground: 0},
	{TiledBackground17: 0},
	{LevelSelectBG: 0},
	{Magnifier: 0},
	{TiledBackground16: 0},
	{Sprite36: 0},
	{Icon: 0},
	{GameManager: 0},
	{Attack: 0},
	{PlayerCollision: 0},
	{Timeline: 0},
	{SmallExplosion: 0},
	{SwordSlash: 0},
	{Sprite37: 0},
	{SoundChip: 0},
	{YAMAHA: 0},
	{Video2: 0},
	{Physics2: 0},
	{Homable: 0},
	{Clickable: 0},
	{Allobjects: 0},
	{Tiles: 0},
	{SolidTiles: 0},
	{Player: 0},
	{Sloped: 0},
	{Monitors: 0},
	{PlayerCollisions: 0},
	{Interactive: 0},
	{Immovable: 0},
	{LocoParts: 0},
	{E3LocoParts: 0},
	{SineVertical: 0},
	{SineHorizontal: 0},
	{BossMovingParts: 0},
	{resumeto: 0},
	{Next: 0},
	{Score: 0},
	{RecentX_Speed: 0},
	{RecentY_Speed: 0},
	{LoaderDone: 0},
	{GameOver: 0},
	{DirectionState: 0},
	{Layout: 0},
	{Layoutis: 0},
	{sideofloop: 0},
	{SavedVolt: 0},
	{Smooth: 0},
	{Freq: 0},
	{HasSave: 0},
	{BGMVolume: 0},
	{BlockCollision: 0},
	{PassthruCollision: 0},
	{ResumetoLayout: 0},
	{CheckpointX: 0},
	{CheckpointY: 0},
	{MouseSpeed: 0},
	{MouseAngle: 0},
	{timer_seconds: 0},
	{timer_minutes: 0},
	{TitleCard_Timer: 0},
	{Continues: 0},
	{Dx: 0},
	{Dy: 0},
	{dew: 0},
	{MyUsername: 0},
	{GAME_NAME: 0},
	{INSTANCE_NAME: 0},
	{ROOM_NAME: 0},
	{DirectionState2: 0},
	{Paused: 0},
	{Selected: 0},
	{RecentLayout: 0},
	{FullscreenType: 0},
	{Full: 0},
	{Selecting: 0},
	{ControlType: 0},
	{ControlTypeNum: 0},
	{LayoutsFinished: 0},
	{ONLMULT: 0},
	{MenuMusic: 0},
	{Firsttimeplaying: 0},
	{NextLayout: 0},
	{Swap: 0},
	{ticks: 0},
	{LvlSlctCodeInput: 0},
	{TimesBeatenTheProto: 0},
	{Paused2: 0},
	{Selected2: 0},
	{RecentLayout2: 0},
	{MusicType2: 0},
	{FullscreenType2: 0},
	{Full2: 0},
	{Selecting2: 0},
	{TestSound2: 0},
	{ControlType2: 0},
	{ControlTypeNum2: 0},
	{LayoutsFinished2: 0},
	{Hz: 0},
	{Region: 0},
	{LevelSelectIndex: 0},
	{LevelSelectIndexString: 0},
	{AnimationName: 0},
	{EnergyBeamOffset: 0},
	{BossHeath: 0},
	{Strength: 0},
	{CenterX: 0},
	{CenterY: 0},
	{HorizontalRandom: 0},
	{VerticalRandom: 0}
];

self.InstanceType = {
	Player_MaskBottom: class extends self.ISpriteInstance {},
	Player_MaskBottomDetector: class extends self.ISpriteInstance {},
	Player_MaskEdgeCheck: class extends self.ISpriteInstance {},
	Player_MaskLeft: class extends self.ISpriteInstance {},
	Player_MaskLeftAngle: class extends self.ISpriteInstance {},
	Player_MaskLeftBig: class extends self.ISpriteInstance {},
	Player_MaskLeftLine: class extends self.ISpriteInstance {},
	Player_MaskMain: class extends self.ISpriteInstance {},
	Player_MaskRight: class extends self.ISpriteInstance {},
	Player_MaskRightAngle: class extends self.ISpriteInstance {},
	Player_MaskRightBig: class extends self.ISpriteInstance {},
	Player_MaskRightLine: class extends self.ISpriteInstance {},
	Player_MaskTop: class extends self.ISpriteInstance {},
	Player_MaskTopBig: class extends self.ISpriteInstance {},
	Player_A_Physics: class extends self.ISpriteInstance {},
	skinToco: class extends self.ISpriteInstance {},
	Player_Mask_Sensor_Collect: class extends self.ISpriteInstance {},
	skinVoltFollower: class extends self.ISpriteInstance {},
	Passhit: class extends self.ISpriteInstance {},
	Player_OnEdgeLeft: class extends self.ISpriteInstance {},
	VoltCameo: class extends self.ISpriteInstance {},
	skinVolt2: class extends self.ISpriteInstance {},
	skinTocoblur: class extends self.ISpriteInstance {},
	Angler: class extends self.ISpriteInstance {},
	White: class extends self.ISpriteInstance {},
	Player_OnEdgeRight: class extends self.ISpriteInstance {},
	DebugObjectSpawner: class extends self.ISpriteInstance {},
	Ring: class extends self.ISpriteInstance {},
	Ring2: class extends self.ISpriteInstance {},
	RingCCount: class extends self.ISpriteInstance {},
	Ring3: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	SpringYellow: class extends self.ISpriteInstance {},
	SpringRed: class extends self.ISpriteInstance {},
	SpeedBooster: class extends self.ISpriteInstance {},
	SpringBlue: class extends self.ISpriteInstance {},
	Spikes: class extends self.ISpriteInstance {},
	_1upmonitor: class extends self.ISpriteInstance {},
	WarningSign: class extends self.ISpriteInstance {},
	Door1: class extends self.ISpriteInstance {},
	EnemyandBoss: class extends self.ISpriteInstance {},
	AirBubbleCreator: class extends self.ISpriteInstance {},
	BigAirbubble: class extends self.ISpriteInstance {},
	Shieldmonitor: class extends self.ISpriteInstance {},
	Shield: class extends self.ISpriteInstance {},
	Invincmonitor: class extends self.ISpriteInstance {},
	Crusher: class extends self.ISpriteInstance {},
	Planet1: class extends self.ISpriteInstance {},
	Planet2: class extends self.ISpriteInstance {},
	Planet3: class extends self.ISpriteInstance {},
	DoorOpener1: class extends self.ISpriteInstance {},
	DoorSensor: class extends self.ISpriteInstance {},
	LvlTxt1: class extends self.ISpriteFontInstance {},
	LvlTxt2: class extends self.ISpriteFontInstance {},
	LvlTxt3: class extends self.ISpriteFontInstance {},
	LvlTxt4: class extends self.ISpriteFontInstance {},
	LvlTxt5: class extends self.ISpriteFontInstance {},
	EjectingSpikes: class extends self.ISpriteInstance {},
	skinDalx: class extends self.ISpriteInstance {},
	Door2: class extends self.ISpriteInstance {},
	Lever1: class extends self.ISpriteInstance {},
	Light1: class extends self.ISpriteInstance {},
	Light2: class extends self.ISpriteInstance {},
	Checkpoint: class extends self.ISpriteInstance {},
	MonitorDebris: class extends self.ISpriteInstance {},
	LocoBody1: class extends self.ISpriteInstance {},
	Wheel1: class extends self.ISpriteInstance {},
	Wheel2: class extends self.ISpriteInstance {},
	Wheel3: class extends self.ISpriteInstance {},
	LocoPlayerCollision: class extends self.ISpriteInstance {},
	LocoBody2: class extends self.ISpriteInstance {},
	LocoPlayerCollision2: class extends self.ISpriteInstance {},
	E3Wheel1: class extends self.ISpriteInstance {},
	E3Wheel2: class extends self.ISpriteInstance {},
	E3Wheel3: class extends self.ISpriteInstance {},
	CargoWheel1: class extends self.ISpriteInstance {},
	CargoWheel2: class extends self.ISpriteInstance {},
	CargoBody1: class extends self.ISpriteInstance {},
	WaterPartical: class extends self.ISpriteInstance {},
	LevelSelectText: class extends self.ISpriteFontInstance {},
	LevelSelectST: class extends self.ISpriteFontInstance {},
	HUD_Life: class extends self.ISpriteFontInstance {},
	HUD_Rings: class extends self.ISpriteFontInstance {},
	HUD_Score: class extends self.ISpriteFontInstance {},
	HUD_Text: class extends self.ISpriteInstance {},
	HUD_TextLife: class extends self.ISpriteInstance {},
	HUD_Time: class extends self.ISpriteFontInstance {},
	HUD_Pause: class extends self.ISpriteInstance {},
	PauseUIResume: class extends self.ISpriteFontInstance {},
	PauseUIBG: class extends self.ISpriteInstance {},
	PauseUIRestart: class extends self.ISpriteFontInstance {},
	PauseUIMainMenu: class extends self.ISpriteFontInstance {},
	HUD_BOSSHEALTH: class extends self.ISpriteFontInstance {},
	PauseUIBorder: class extends self.ISpriteInstance {},
	PauseUIGrayscaler: class extends self.ISpriteInstance {},
	TitleCard_Banner: class extends self.ISpriteInstance {},
	TitleCard_Black: class extends self.ISpriteInstance {},
	TitleCard_NameStage: class extends self.ISpriteFontInstance {},
	TitleCard_Zone: class extends self.ISpriteInstance {},
	TitleCard_Zone2Act: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	TocoJoging: class extends self.ISpriteInstance {},
	VoltJoging: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	TitleLogo: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	LayoutsComplete: class extends self.ISpriteFontInstance {},
	Options: class extends self.ISpriteFontInstance {},
	Start: class extends self.ISpriteFontInstance {},
	MusicPlaying: class extends self.ISpriteFontInstance {},
	TTHTitleLay: class extends self.ISpriteInstance {},
	TTHTitleLay2Bmp: class extends self.ISpriteInstance {},
	costume: class extends self.ISpriteInstance {},
	Continue: class extends self.ISpriteFontInstance {},
	OptionsMusicDisplay: class extends self.ISpriteFontInstance {},
	OptionsMusicType: class extends self.ISpriteFontInstance {},
	CreditsText: class extends self.ISpriteFontInstance {},
	OptionsFullscreenText: class extends self.ISpriteFontInstance {},
	OptionsFullscreenType: class extends self.ISpriteFontInstance {},
	OptionsSoundTestText: class extends self.ISpriteFontInstance {},
	z: class extends self.ISpriteFontInstance {},
	OptionsSoundTestDisplay: class extends self.ISpriteFontInstance {},
	OptionsControlTypeText: class extends self.ISpriteFontInstance {},
	OptionsControlTypeInput: class extends self.ISpriteFontInstance {},
	VersionTxt1: class extends self.ISpriteFontInstance {},
	Layout1Text: class extends self.ISpriteFontInstance {},
	Layout1Text2: class extends self.ISpriteFontInstance {},
	Layout1Text3: class extends self.ISpriteFontInstance {},
	Layout1Text4: class extends self.ISpriteFontInstance {},
	Layout1Text5: class extends self.ISpriteFontInstance {},
	OptionsBGMVolumeText: class extends self.ISpriteFontInstance {},
	OptionsBGMVolumeDisplay: class extends self.ISpriteFontInstance {},
	LoadingTxt: class extends self.ISpriteFontInstance {},
	OptionsONLMULT: class extends self.ISpriteFontInstance {},
	TitleLogo2: class extends self.ISpriteInstance {},
	TheTime: class extends self.ISpriteFontInstance {},
	OptionsMainMenuMusictype: class extends self.ISpriteFontInstance {},
	SystemCamera: class extends self.ISpriteInstance {},
	SystemFade: class extends self.ISpriteInstance {},
	SystemFade2: class extends self.ISpriteInstance {},
	WrapperBottom: class extends self.ISpriteInstance {},
	WrapperTop: class extends self.ISpriteInstance {},
	Ramp3: class extends self.ISpriteInstance {},
	QuarterCircle1: class extends self.ISpriteInstance {},
	QuarterCircle2: class extends self.ISpriteInstance {},
	QuarterCircle3: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Slope1: class extends self.ISpriteInstance {},
	_2x2Block: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	Block2: class extends self.ISpriteInstance {},
	Slope3: class extends self.ISpriteInstance {},
	QuarterCircle4: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Ramp1: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	RollerBlock: class extends self.ISpriteInstance {},
	halfblock: class extends self.ISpriteInstance {},
	PassthuBlock: class extends self.ISpriteInstance {},
	Wedge: class extends self.ISpriteInstance {},
	Wedge2: class extends self.ISpriteInstance {},
	Wedge3: class extends self.ISpriteInstance {},
	Ramp2: class extends self.ISpriteInstance {},
	_3quarterBlock: class extends self.ISpriteInstance {},
	Blockx2: class extends self.ISpriteInstance {},
	Blockx4: class extends self.ISpriteInstance {},
	LeftLoopdetecter: class extends self.ISpriteInstance {},
	RightLoopdeloopbottom: class extends self.ISpriteInstance {},
	RightLoopdetecter: class extends self.ISpriteInstance {},
	LeftLoopdeloopbottom: class extends self.ISpriteInstance {},
	RightMiddle: class extends self.ISpriteInstance {},
	LeftMiddle: class extends self.ISpriteInstance {},
	_2x2Blocknocollision: class extends self.ISpriteInstance {},
	PassthuBlock2: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Rod: class extends self.ISpriteInstance {},
	Rod2: class extends self.ISpriteInstance {},
	RodCollision: class extends self.ISpriteInstance {},
	Slope2: class extends self.ISpriteInstance {},
	FloatingBlockx4: class extends self.ISpriteInstance {},
	FloatingBlockX: class extends self.ISpriteInstance {},
	_4x4Block: class extends self.ISpriteInstance {},
	Glider: class extends self.ITiledBackgroundInstance {},
	_4x2Block: class extends self.ISpriteInstance {},
	PassableRamp: class extends self.ISpriteInstance {},
	BGLayer1: class extends self.ITiledBackgroundInstance {},
	BGLayer2: class extends self.ITiledBackgroundInstance {},
	BGLayer3: class extends self.ITiledBackgroundInstance {},
	BGLayer4: class extends self.ITiledBackgroundInstance {},
	BGLayer0: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	RollerBlockStart: class extends self.ISpriteInstance {},
	RollerBlockEnd: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	MML1BG: class extends self.ITiledBackgroundInstance {},
	MML1BG2: class extends self.ITiledBackgroundInstance {},
	_2x2Blocknocollision2: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	Ramp4: class extends self.ISpriteInstance {},
	Gliderwithcollision1: class extends self.ISpriteInstance {},
	Glider2: class extends self.ITiledBackgroundInstance {},
	Gliders: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Blockdetecter1: class extends self.ISpriteInstance {},
	Blockdetecter2: class extends self.ISpriteInstance {},
	PassthruOff: class extends self.ISpriteInstance {},
	PassthruOn: class extends self.ISpriteInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	Shocker: class extends self.ITiledBackgroundInstance {},
	TileBlock: class extends self.ITiledBackgroundInstance {},
	_2x2Block2: class extends self.ISpriteInstance {},
	Water2: class extends self.ISpriteInstance {},
	Effect_SkiddingDust: class extends self.ISpriteInstance {},
	Effect_Spindash: class extends self.ISpriteInstance {},
	Effect_Explosion: class extends self.ISpriteInstance {},
	Splash: class extends self.ISpriteInstance {},
	Effects_Sparkle: class extends self.ISpriteInstance {},
	Effects_Sparkle2: class extends self.ISpriteInstance {},
	Effect_Burst: class extends self.ISpriteInstance {},
	Effects_Sparkle3: class extends self.ISpriteInstance {},
	Effects_Sparkle4: class extends self.ISpriteInstance {},
	Effect_Electricity: class extends self.ISpriteInstance {},
	Loco_Exaust: class extends self.IParticlesInstance {},
	Loco_Exaust2: class extends self.IParticlesInstance {},
	Loco_Exaust3: class extends self.IParticlesInstance {},
	Loco_Exaust4: class extends self.IParticlesInstance {},
	E3Loco_Exaust: class extends self.IParticlesInstance {},
	WaterWaves: class extends self.ISpriteInstance {},
	TPad_Action: class extends self.ISpriteInstance {},
	Touch_Down: class extends self.ISpriteInstance {},
	Touch_Left: class extends self.ISpriteInstance {},
	Touch_Right: class extends self.ISpriteInstance {},
	Touch_Up: class extends self.ISpriteInstance {},
	TPad_Control: class extends self.ISpriteInstance {},
	Player_Input: class extends self.ISpriteInstance {},
	TPad_Quickdash: class extends self.ISpriteInstance {},
	TPad_Speedometer: class extends self.ISpriteInstance {},
	TPad_Speedometer2: class extends self.ISpriteInstance {},
	TPad_Combat: class extends self.ISpriteInstance {},
	MenuLeftInput: class extends self.ISpriteInstance {},
	MenuRightInput: class extends self.ISpriteInstance {},
	MenuSelectInput: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	Player_Input2: class extends self.ISpriteInstance {},
	TPad_Speedometer3: class extends self.ISpriteInstance {},
	Player_MaskBottom2: class extends self.ISpriteInstance {},
	Player_MaskBottomDetector2: class extends self.ISpriteInstance {},
	Player_MaskEdgeCheck2: class extends self.ISpriteInstance {},
	Player_MaskLeft2: class extends self.ISpriteInstance {},
	Player_MaskLeftAngle2: class extends self.ISpriteInstance {},
	Player_MaskLeftBig2: class extends self.ISpriteInstance {},
	Player_MaskLeftLine2: class extends self.ISpriteInstance {},
	Player_MaskMain2: class extends self.ISpriteInstance {},
	Player_MaskRight2: class extends self.ISpriteInstance {},
	Player_MaskRightAngle2: class extends self.ISpriteInstance {},
	Player_MaskRightBig2: class extends self.ISpriteInstance {},
	Player_MaskRightLine2: class extends self.ISpriteInstance {},
	Player_MaskTop2: class extends self.ISpriteInstance {},
	Player_MaskTopBig2: class extends self.ISpriteInstance {},
	Player_B_Physics: class extends self.ISpriteInstance {},
	skinVolt: class extends self.ISpriteInstance {},
	Player_Mask_Sensor_Collect2: class extends self.ISpriteInstance {},
	skinVoltFollower2: class extends self.ISpriteInstance {},
	Passhit2: class extends self.ISpriteInstance {},
	Player_OnEdgeLeft2: class extends self.ISpriteInstance {},
	VoltCameo2: class extends self.ISpriteInstance {},
	skinVolt3: class extends self.ISpriteInstance {},
	Angler2: class extends self.ISpriteInstance {},
	White2: class extends self.ISpriteInstance {},
	EyeFire: class extends self.ISpriteInstance {},
	EnergyBeam: class extends self.ITiledBackgroundInstance {},
	BossHips: class extends self.ISpriteInstance {},
	BossHead: class extends self.ISpriteInstance {},
	BossFrontArm: class extends self.ISpriteInstance {},
	BossChest: class extends self.ISpriteInstance {},
	BossBackArm: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	EyeFlash: class extends self.ISpriteInstance {},
	FireBall: class extends self.ISpriteInstance {},
	FireBallTrail: class extends self.ISpriteInstance {},
	FrontArmTrail: class extends self.ISpriteInstance {},
	GroundDebri: class extends self.ISpriteInstance {},
	BigExplosion: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Goal: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Back: class extends self.ISpriteFontInstance {},
	SondrixLogo: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sondrix: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	Untitled11_: class extends self.ISpriteInstance {},
	dczd4eg83f90a47ff0c432e9c56b64ccd85d16c: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	GameOverText: class extends self.ITextInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	GoalWall: class extends self.ISpriteInstance {},
	GoalCover: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	ResultsUITotalScoreText: class extends self.ITextInstance {},
	ResultsUIMadeitText: class extends self.ITextInstance {},
	ResultsUIRingsText: class extends self.ITextInstance {},
	ResultsUITimeText: class extends self.ITextInstance {},
	ResultsUITime: class extends self.ITextInstance {},
	ResultsUIRing: class extends self.ITextInstance {},
	ResultsUITotalScore: class extends self.ITextInstance {},
	Gamepad: class extends self.IInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Dont: class extends self.ITextInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	LocalStorage: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Mute: class extends self.ISpriteInstance {},
	Killer: class extends self.ISpriteInstance {},
	FileSystem: class extends self.IInstance {},
	SpriteFont4: class extends self.ISpriteFontInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	VoltIcon: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Bluetooth: class extends self.IInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Emblem: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Multiplayer: class extends self.IInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	GoalCover2: class extends self.ISpriteInstance {},
	ConstructLogo: class extends self.ISpriteInstance {},
	ConstuctText: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	VideoRecorder: class extends self.IInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	ContinueIcon: class extends self.ISpriteInstance {},
	Template1: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	Date: class extends self.IInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Buildings: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Button: class extends self.IButtonInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	Text2: class extends self.ITextInstance {},
	SliderBar2: class extends self.ISliderBarInstance {},
	SondrixLetter: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Static: class extends self.ISpriteInstance {},
	SondrixLoadingthing: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	Banner: class extends self.ISpriteInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Glass: class extends self.ISpriteInstance {},
	SonicCameo: class extends self.ISpriteInstance {},
	Text3: class extends self.ITextInstance {},
	NiseEU: class extends self.ISpriteFontInstance {},
	SonicFollower: class extends self.ISpriteInstance {},
	TitlecardLetters: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	IIL1BG1: class extends self.ITiledBackgroundInstance {},
	IIL1Clouds: class extends self.ITiledBackgroundInstance {},
	IIL1BG2: class extends self.ITiledBackgroundInstance {},
	SCL2BG1: class extends self.ITiledBackgroundInstance {},
	Cloud1: class extends self.ITiledBackgroundInstance {},
	Cloud2: class extends self.ITiledBackgroundInstance {},
	Cloud3: class extends self.ITiledBackgroundInstance {},
	Cloud4: class extends self.ITiledBackgroundInstance {},
	Cloud5: class extends self.ITiledBackgroundInstance {},
	Cloud6: class extends self.ITiledBackgroundInstance {},
	Cloud7: class extends self.ITiledBackgroundInstance {},
	TiledBackground23: class extends self.ITiledBackgroundInstance {},
	TiledBackground24: class extends self.ITiledBackgroundInstance {},
	LocoRod: class extends self.ISpriteInstance {},
	PPL1BG1: class extends self.ITiledBackgroundInstance {},
	PPL1BG2: class extends self.ITiledBackgroundInstance {},
	PPL1BG3: class extends self.ITiledBackgroundInstance {},
	PPL1BG4: class extends self.ITiledBackgroundInstance {},
	PPL1BG5: class extends self.ITiledBackgroundInstance {},
	Particles2: class extends self.IParticlesInstance {},
	E3LocoRod1: class extends self.ISpriteInstance {},
	IIL1Foreground: class extends self.ITiledBackgroundInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	LevelSelectBG: class extends self.ITiledBackgroundInstance {},
	Magnifier: class extends self.ISpriteInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Icon: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	PlayerCollision: class extends self.ISpriteInstance {},
	Ground: class extends self.ITilemapInstance {},
	Timeline: class extends self.IInstance {},
	SmallExplosion: class extends self.ISpriteInstance {},
	SwordSlash: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	SoundChip: class extends self.ISpriteInstance {},
	YAMAHA: class extends self.ISpriteInstance {},
	Video2: class extends self.IWorldInstance {},
	Solid: class extends self.ISpriteInstance {},
	Homable: class extends self.ISpriteInstance {},
	Clickable: class extends self.ISpriteInstance {},
	Allobjects: class extends self.ISpriteInstance {},
	Tiles: class extends self.ITiledBackgroundInstance {},
	SolidTiles: class extends self.ITiledBackgroundInstance {},
	Player: class extends self.ISpriteInstance {},
	Sloped: class extends self.ISpriteInstance {},
	Monitors: class extends self.ISpriteInstance {},
	PlayerCollisions: class extends self.ISpriteInstance {},
	Interactive: class extends self.ISpriteInstance {},
	Immovable: class extends self.ISpriteInstance {},
	LocoParts: class extends self.ISpriteInstance {},
	E3LocoParts: class extends self.ISpriteInstance {},
	BossMovingParts: class extends self.ISpriteInstance {}
}